"""
state.py — Shared state definition and Pydantic validation models
for Multi-Agentic AI Personal Savings Recommendation System.
"""

from typing import TypedDict, List, Dict, Any, Optional
from pydantic import BaseModel, Field


class AnalysisState(TypedDict):
    """
    Shared blackboard state object passed across all agents.
    Every agent reads from this state and writes its verified findings.
    """
    profile: dict            # income, expenses by category, goal, deadline, existing savings, etc.
    constraints: dict        # e.g. {"protect_essentials": True, "target_extra_savings": 10000, "rejected_reasons": []}
    findings: dict           # {"expense": {...}, "budget": {...}, "goal": {...}}
    candidate_strategies: list # generated by Savings Recommendation Agent
    validated_strategies: list # approved/modified by Safety/Feasibility Agent
    reasoning_log: list[str]  # one line per agent action, for UI streaming and demo inspection
    status: str              # "initialized", "expense_analyzed", "budget_analyzed", "goal_analyzed", "revising", "completed", "error"


# ---------------------------------------------------------------------------
# Pydantic Schemas for Agent Structured Outputs (Validation & Type Safety)
# ---------------------------------------------------------------------------

class ExpenseAgentOutput(BaseModel):
    category_totals: Dict[str, float] = Field(description="Total expense for each category")
    essential_total: float = Field(description="Sum of essential expenses (rent, base groceries, utilities, debt)")
    discretionary_total: float = Field(description="Sum of discretionary expenses (dining out, shopping, subscriptions, entertainment)")
    recurring_items: List[Dict[str, Any]] = Field(default_factory=list, description="Recurring detected expenses")
    reasoning: str = Field(description="Summary of expense breakdown")


class BudgetAgentOutput(BaseModel):
    total_income: float = Field(description="Total monthly income")
    total_expenses: float = Field(description="Total monthly expenses")
    current_savings: float = Field(description="Current monthly savings (income - expenses)")
    savings_rate: float = Field(description="Savings rate as percentage (0-100)")
    discretionary_capacity: float = Field(description="Safe cut capacity from discretionary spending")
    health_status: str = Field(description="Budget health rating: Healthy, Strained, or Deficit")
    reasoning: str = Field(description="Budget agent summary")


class GoalAgentOutput(BaseModel):
    goal_amount: float = Field(description="Target savings amount")
    deadline_months: int = Field(description="Goal deadline in months")
    current_savings_rate: float = Field(description="Current monthly savings rate")
    required_monthly_saving: float = Field(description="Monthly saving needed to hit goal on time")
    gap_vs_current: float = Field(description="Difference between required and current monthly savings (positive means shortfall)")
    is_feasible_with_current: bool = Field(description="Whether goal is attainable without additional cuts")
    projected_completion_months: float = Field(description="Estimated months to reach goal at current savings rate")
    reasoning: str = Field(description="Goal feasibility assessment")


class StrategyItem(BaseModel):
    name: str = Field(description="Short human-friendly title for the strategy")
    action: str = Field(description="Actionable description of the cut or reallocation")
    category: str = Field(description="Target category (e.g., dining_out, shopping, subscriptions, composite)")
    reduction_percent: float = Field(default=0.0, description="Percentage cut in target category")
    estimated_monthly_saving: float = Field(description="Exact tool-calculated monthly savings amount")
    annual_impact: float = Field(default=0.0, description="Annualized saving (12x monthly saving)")
    reason: str = Field(description="Plain language explanation and justification")
    risk_level: str = Field(default="Low", description="Risk level: Low, Moderate, or High")
    status: str = Field(default="candidate", description="candidate, approved, modified, or rejected")
    safety_notes: Optional[str] = Field(default=None, description="Notes or rejection feedback from Safety Agent")


class SavingsAgentOutput(BaseModel):
    strategies: List[StrategyItem] = Field(description="2 to 4 recommended candidate savings strategies")
    revision_count: int = Field(default=0, description="Number of revisions attempted")
    reasoning: str = Field(description="Explanation of why these candidate strategies were selected")


class SafetyEvaluationItem(BaseModel):
    strategy_name: str
    decision: str = Field(description="'approved', 'modified', or 'rejected'")
    reason: str = Field(description="Safety justification, floor checks, or rejection explanation")
    suggested_fix: Optional[str] = Field(default=None, description="Guidance if rejected or modified")


class SafetyAgentOutput(BaseModel):
    overall_approved: bool = Field(description="True if all strategies pass, False if any require revision")
    evaluations: List[SafetyEvaluationItem] = Field(description="Individual strategy evaluations")
    rejection_reasons: List[str] = Field(default_factory=list, description="Explicit reasons for rejected strategies to feed back to Savings Agent")
    reasoning: str = Field(description="Safety summary")
